#pragma once

const char* slime_data(){
    return R"(
<?xml version="1.0"?>
<data>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/front/slime_front_1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/left/slime_left_1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/right/slime_right_1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/back/slime_back_1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/front/slime_front_1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_front_2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_front_1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_front_3.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/left/slime_left_1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/left/slime_left_2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/left/slime_left_1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/left/slime_left_3.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/right/slime_right_1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/right/slime_right_2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/right/slime_right_1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/right/slime_right_3.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/back/slime_back_1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/back/slime_back_2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/back/slime_back_1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/back/slime_back_3.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/front/slime_front_1.png</filename>
            <duration>250</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_front_2.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_front_1.png</filename>
            <duration>250</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/front/slime_left_1.png</filename>
            <duration>250</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_left_2.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_left_1.png</filename>
            <duration>250</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/front/slime_right_1.png</filename>
            <duration>250</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_right_2.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_right_1.png</filename>
            <duration>250</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/front/slime_back_1.png</filename>
            <duration>250</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_back_2.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/slime_back_1.png</filename>
            <duration>250</duration>
        </frame>
    </animation>
</data>
)";
}
