#pragma once

#include <string>
#include <map>
#include <vector>
#include "xml_data.h"

inline XMLData* slime_object_data(){
	XMLData* next_storage_0 = new XMLData(std::string(""));
	next_storage_0->tag = "root";
	XMLData* next_storage_1 = new XMLData(std::string("slime"));
	next_storage_1->tag = "name";
	next_storage_0->nexts["name"].push_back(next_storage_1);
	XMLData* next_storage_2 = new XMLData(std::string("Normal"));
	next_storage_2->tag = "type";
	next_storage_0->nexts["type"].push_back(next_storage_2);
	XMLData* next_storage_3 = new XMLData(std::string(""));
	next_storage_3->tag = "transform";
	XMLData* next_storage_4 = new XMLData(std::string(""));
	next_storage_4->tag = "position";
	XMLData* next_storage_5 = new XMLData(std::string("320.0"));
	next_storage_5->tag = "x";
	next_storage_4->nexts["x"].push_back(next_storage_5);
	XMLData* next_storage_6 = new XMLData(std::string("0.0"));
	next_storage_6->tag = "y";
	next_storage_4->nexts["y"].push_back(next_storage_6);
	XMLData* next_storage_7 = new XMLData(std::string("0.0"));
	next_storage_7->tag = "z";
	next_storage_4->nexts["z"].push_back(next_storage_7);
	next_storage_3->nexts["position"].push_back(next_storage_4);
	XMLData* next_storage_8 = new XMLData(std::string(""));
	next_storage_8->tag = "rotation";
	XMLData* next_storage_9 = new XMLData(std::string("0.0"));
	next_storage_9->tag = "x";
	next_storage_8->nexts["x"].push_back(next_storage_9);
	XMLData* next_storage_10 = new XMLData(std::string("0.0"));
	next_storage_10->tag = "y";
	next_storage_8->nexts["y"].push_back(next_storage_10);
	XMLData* next_storage_11 = new XMLData(std::string("0.0"));
	next_storage_11->tag = "z";
	next_storage_8->nexts["z"].push_back(next_storage_11);
	next_storage_3->nexts["rotation"].push_back(next_storage_8);
	XMLData* next_storage_12 = new XMLData(std::string(""));
	next_storage_12->tag = "scale";
	XMLData* next_storage_13 = new XMLData(std::string("2.0"));
	next_storage_13->tag = "x";
	next_storage_12->nexts["x"].push_back(next_storage_13);
	XMLData* next_storage_14 = new XMLData(std::string("2.0"));
	next_storage_14->tag = "y";
	next_storage_12->nexts["y"].push_back(next_storage_14);
	XMLData* next_storage_15 = new XMLData(std::string("1.0"));
	next_storage_15->tag = "z";
	next_storage_12->nexts["z"].push_back(next_storage_15);
	next_storage_3->nexts["scale"].push_back(next_storage_12);
	next_storage_0->nexts["transform"].push_back(next_storage_3);
	XMLData* next_storage_16 = new XMLData(std::string(""));
	next_storage_16->tag = "component";
	XMLData* next_storage_17 = new XMLData(std::string(""));
	next_storage_17->tag = "animation_image";
	XMLData* next_storage_18 = new XMLData(std::string("slime_anim_data"));
	next_storage_18->tag = "data_name";
	next_storage_17->nexts["data_name"].push_back(next_storage_18);
	XMLData* next_storage_19 = new XMLData(std::string(""));
	next_storage_19->tag = "offset";
	XMLData* next_storage_20 = new XMLData(std::string("0"));
	next_storage_20->tag = "x";
	next_storage_19->nexts["x"].push_back(next_storage_20);
	XMLData* next_storage_21 = new XMLData(std::string("-16"));
	next_storage_21->tag = "y";
	next_storage_19->nexts["y"].push_back(next_storage_21);
	next_storage_17->nexts["offset"].push_back(next_storage_19);
	XMLData* next_storage_22 = new XMLData(std::string("255"));
	next_storage_22->tag = "image_alpha";
	next_storage_17->nexts["image_alpha"].push_back(next_storage_22);
	XMLData* next_storage_23 = new XMLData(std::string("2"));
	next_storage_23->tag = "image_layer";
	next_storage_17->nexts["image_layer"].push_back(next_storage_23);
	next_storage_16->nexts["animation_image"].push_back(next_storage_17);
	next_storage_0->nexts["component"].push_back(next_storage_16);
	XMLData* next_storage_24 = new XMLData(std::string(""));
	next_storage_24->tag = "component";
	XMLData* next_storage_25 = new XMLData(std::string(""));
	next_storage_25->tag = "animator2d";
	XMLData* next_storage_26 = new XMLData(std::string("0"));
	next_storage_26->tag = "anim_root_id";
	next_storage_25->nexts["anim_root_id"].push_back(next_storage_26);
	XMLData* next_storage_27 = new XMLData(std::string("CAT_AnimationImage"));
	next_storage_27->tag = "anim_type";
	next_storage_25->nexts["anim_type"].push_back(next_storage_27);
	XMLData* next_storage_28 = new XMLData(std::string("player_anim_tuple"));
	next_storage_28->tag = "animation_sets";
	next_storage_25->nexts["animation_sets"].push_back(next_storage_28);
	next_storage_24->nexts["animator2d"].push_back(next_storage_25);
	next_storage_0->nexts["component"].push_back(next_storage_24);
	XMLData* next_storage_29 = new XMLData(std::string(""));
	next_storage_29->tag = "component";
	XMLData* next_storage_30 = new XMLData(std::string(""));
	next_storage_30->tag = "rigidbody";
	XMLData* next_storage_31 = new XMLData(std::string("Newton"));
	next_storage_31->tag = "type";
	next_storage_30->nexts["type"].push_back(next_storage_31);
	XMLData* next_storage_32 = new XMLData(std::string("4.0"));
	next_storage_32->tag = "mass";
	next_storage_30->nexts["mass"].push_back(next_storage_32);
	XMLData* next_storage_33 = new XMLData(std::string("1.0"));
	next_storage_33->tag = "coefficient";
	next_storage_30->nexts["coefficient"].push_back(next_storage_33);
	XMLData* next_storage_34 = new XMLData(std::string("1.0"));
	next_storage_34->tag = "friction_coefficient";
	next_storage_30->nexts["friction_coefficient"].push_back(next_storage_34);
	XMLData* next_storage_35 = new XMLData(std::string(""));
	next_storage_35->tag = "virtual_normal_force";
	XMLData* next_storage_36 = new XMLData(std::string("0.0"));
	next_storage_36->tag = "x";
	next_storage_35->nexts["x"].push_back(next_storage_36);
	XMLData* next_storage_37 = new XMLData(std::string("0.0"));
	next_storage_37->tag = "y";
	next_storage_35->nexts["y"].push_back(next_storage_37);
	XMLData* next_storage_38 = new XMLData(std::string("1000.0"));
	next_storage_38->tag = "z";
	next_storage_35->nexts["z"].push_back(next_storage_38);
	next_storage_30->nexts["virtual_normal_force"].push_back(next_storage_35);
	next_storage_29->nexts["rigidbody"].push_back(next_storage_30);
	next_storage_0->nexts["component"].push_back(next_storage_29);
	XMLData* next_storage_39 = new XMLData(std::string(""));
	next_storage_39->tag = "component";
	XMLData* next_storage_40 = new XMLData(std::string(""));
	next_storage_40->tag = "virtual_controller";
	XMLData* next_storage_41 = new XMLData(std::string("0"));
	next_storage_41->tag = "rigidbody_id";
	next_storage_40->nexts["rigidbody_id"].push_back(next_storage_41);
	XMLData* next_storage_42 = new XMLData(std::string("10.0"));
	next_storage_42->tag = "input_speed";
	next_storage_40->nexts["input_speed"].push_back(next_storage_42);
	XMLData* next_storage_43 = new XMLData(std::string("170.0"));
	next_storage_43->tag = "max_speed";
	next_storage_40->nexts["max_speed"].push_back(next_storage_43);
	next_storage_39->nexts["virtual_controller"].push_back(next_storage_40);
	next_storage_0->nexts["component"].push_back(next_storage_39);
	XMLData* next_storage_44 = new XMLData(std::string(""));
	next_storage_44->tag = "component";
	XMLData* next_storage_45 = new XMLData(std::string(""));
	next_storage_45->tag = "box_collider2d";
	XMLData* next_storage_46 = new XMLData(std::string("0"));
	next_storage_46->tag = "layer";
	next_storage_45->nexts["layer"].push_back(next_storage_46);
	XMLData* next_storage_47 = new XMLData(std::string("4500"));
	next_storage_47->tag = "magnitude";
	next_storage_45->nexts["magnitude"].push_back(next_storage_47);
	XMLData* next_storage_48 = new XMLData(std::string("1"));
	next_storage_48->tag = "collision";
	next_storage_45->nexts["collision"].push_back(next_storage_48);
	XMLData* next_storage_49 = new XMLData(std::string("16.0"));
	next_storage_49->tag = "w";
	next_storage_45->nexts["w"].push_back(next_storage_49);
	XMLData* next_storage_50 = new XMLData(std::string("16.0"));
	next_storage_50->tag = "h";
	next_storage_45->nexts["h"].push_back(next_storage_50);
	XMLData* next_storage_51 = new XMLData(std::string(""));
	next_storage_51->tag = "offset";
	XMLData* next_storage_52 = new XMLData(std::string("0"));
	next_storage_52->tag = "x";
	next_storage_51->nexts["x"].push_back(next_storage_52);
	XMLData* next_storage_53 = new XMLData(std::string("0"));
	next_storage_53->tag = "y";
	next_storage_51->nexts["y"].push_back(next_storage_53);
	next_storage_45->nexts["offset"].push_back(next_storage_51);
	XMLData* next_storage_54 = new XMLData(std::string("0"));
	next_storage_54->tag = "rigidbody_id";
	next_storage_45->nexts["rigidbody_id"].push_back(next_storage_54);
	next_storage_44->nexts["box_collider2d"].push_back(next_storage_45);
	next_storage_0->nexts["component"].push_back(next_storage_44);
	XMLData* next_storage_55 = new XMLData(std::string(""));
	next_storage_55->tag = "component";
	XMLData* next_storage_56 = new XMLData(std::string(""));
	next_storage_56->tag = "nav_mesh_agent2d";
	XMLData* next_storage_57 = new XMLData(std::string("player"));
	next_storage_57->tag = "target_object_name";
	next_storage_56->nexts["target_object_name"].push_back(next_storage_57);
	XMLData* next_storage_58 = new XMLData(std::string("0"));
	next_storage_58->tag = "target_transform_id";
	next_storage_56->nexts["target_transform_id"].push_back(next_storage_58);
	next_storage_55->nexts["nav_mesh_agent2d"].push_back(next_storage_56);
	next_storage_0->nexts["component"].push_back(next_storage_55);
	XMLData* next_storage_59 = new XMLData(std::string(""));
	next_storage_59->tag = "component";
	XMLData* next_storage_60 = new XMLData(std::string(""));
	next_storage_60->tag = "slime_controller";
	XMLData* next_storage_61 = new XMLData(std::string("0"));
	next_storage_61->tag = "rigidbody_id";
	next_storage_60->nexts["rigidbody_id"].push_back(next_storage_61);
	XMLData* next_storage_62 = new XMLData(std::string("0"));
	next_storage_62->tag = "virtual_controller_id";
	next_storage_60->nexts["virtual_controller_id"].push_back(next_storage_62);
	XMLData* next_storage_63 = new XMLData(std::string("0"));
	next_storage_63->tag = "animator2D_id";
	next_storage_60->nexts["animator2D_id"].push_back(next_storage_63);
	XMLData* next_storage_64 = new XMLData(std::string("0"));
	next_storage_64->tag = "nav_mesh_agent_id";
	next_storage_60->nexts["nav_mesh_agent_id"].push_back(next_storage_64);
	next_storage_59->nexts["slime_controller"].push_back(next_storage_60);
	next_storage_0->nexts["component"].push_back(next_storage_59);
	XMLData* next_storage_65 = new XMLData(std::string(""));
	next_storage_65->tag = "other_object_components";
	XMLData* next_storage_66 = new XMLData(std::string("player"));
	next_storage_66->tag = "object";
	XMLData* next_storage_67 = new XMLData(std::string("CAT_Transform"));
	next_storage_67->tag = "component";
	next_storage_66->nexts["component"].push_back(next_storage_67);
	XMLData* next_storage_68 = new XMLData(std::string("0"));
	next_storage_68->tag = "component_id";
	next_storage_66->nexts["component_id"].push_back(next_storage_68);
	next_storage_65->nexts["object"].push_back(next_storage_66);
	next_storage_0->nexts["other_object_components"].push_back(next_storage_65);
	return next_storage_0;
}