#pragma once

#include <string>
#include <map>
#include <vector>
#include "xml_data.h"

inline XMLData* nav_mesh_rect1(){
	XMLData* next_storage_0 = new XMLData(std::string("	"));
	next_storage_0->tag = "root";
	XMLData* next_storage_1 = new XMLData(std::string("		"));
	next_storage_1->tag = "rect";
	XMLData* next_storage_2 = new XMLData(std::string("0"));
	next_storage_2->tag = "id";
	next_storage_1->nexts["id"].push_back(next_storage_2);
	XMLData* next_storage_3 = new XMLData(std::string("80.0"));
	next_storage_3->tag = "x";
	next_storage_1->nexts["x"].push_back(next_storage_3);
	XMLData* next_storage_4 = new XMLData(std::string("96.0"));
	next_storage_4->tag = "y";
	next_storage_1->nexts["y"].push_back(next_storage_4);
	XMLData* next_storage_5 = new XMLData(std::string("48.0"));
	next_storage_5->tag = "width";
	next_storage_1->nexts["width"].push_back(next_storage_5);
	XMLData* next_storage_6 = new XMLData(std::string("64.0"));
	next_storage_6->tag = "height";
	next_storage_1->nexts["height"].push_back(next_storage_6);
	next_storage_0->nexts["rect"].push_back(next_storage_1);
	XMLData* next_storage_7 = new XMLData(std::string("		"));
	next_storage_7->tag = "rect";
	XMLData* next_storage_8 = new XMLData(std::string("1"));
	next_storage_8->tag = "id";
	next_storage_7->nexts["id"].push_back(next_storage_8);
	XMLData* next_storage_9 = new XMLData(std::string("160.0"));
	next_storage_9->tag = "x";
	next_storage_7->nexts["x"].push_back(next_storage_9);
	XMLData* next_storage_10 = new XMLData(std::string("96.0"));
	next_storage_10->tag = "y";
	next_storage_7->nexts["y"].push_back(next_storage_10);
	XMLData* next_storage_11 = new XMLData(std::string("32.0"));
	next_storage_11->tag = "width";
	next_storage_7->nexts["width"].push_back(next_storage_11);
	XMLData* next_storage_12 = new XMLData(std::string("64.0"));
	next_storage_12->tag = "height";
	next_storage_7->nexts["height"].push_back(next_storage_12);
	next_storage_0->nexts["rect"].push_back(next_storage_7);
	XMLData* next_storage_13 = new XMLData(std::string("		"));
	next_storage_13->tag = "rect";
	XMLData* next_storage_14 = new XMLData(std::string("2"));
	next_storage_14->tag = "id";
	next_storage_13->nexts["id"].push_back(next_storage_14);
	XMLData* next_storage_15 = new XMLData(std::string("320.0"));
	next_storage_15->tag = "x";
	next_storage_13->nexts["x"].push_back(next_storage_15);
	XMLData* next_storage_16 = new XMLData(std::string("96.0"));
	next_storage_16->tag = "y";
	next_storage_13->nexts["y"].push_back(next_storage_16);
	XMLData* next_storage_17 = new XMLData(std::string("128.0"));
	next_storage_17->tag = "width";
	next_storage_13->nexts["width"].push_back(next_storage_17);
	XMLData* next_storage_18 = new XMLData(std::string("64.0"));
	next_storage_18->tag = "height";
	next_storage_13->nexts["height"].push_back(next_storage_18);
	next_storage_0->nexts["rect"].push_back(next_storage_13);
	XMLData* next_storage_19 = new XMLData(std::string("		"));
	next_storage_19->tag = "rect";
	XMLData* next_storage_20 = new XMLData(std::string("3"));
	next_storage_20->tag = "id";
	next_storage_19->nexts["id"].push_back(next_storage_20);
	XMLData* next_storage_21 = new XMLData(std::string("480.0"));
	next_storage_21->tag = "x";
	next_storage_19->nexts["x"].push_back(next_storage_21);
	XMLData* next_storage_22 = new XMLData(std::string("96.0"));
	next_storage_22->tag = "y";
	next_storage_19->nexts["y"].push_back(next_storage_22);
	XMLData* next_storage_23 = new XMLData(std::string("32.0"));
	next_storage_23->tag = "width";
	next_storage_19->nexts["width"].push_back(next_storage_23);
	XMLData* next_storage_24 = new XMLData(std::string("64.0"));
	next_storage_24->tag = "height";
	next_storage_19->nexts["height"].push_back(next_storage_24);
	next_storage_0->nexts["rect"].push_back(next_storage_19);
	XMLData* next_storage_25 = new XMLData(std::string("		"));
	next_storage_25->tag = "rect";
	XMLData* next_storage_26 = new XMLData(std::string("4"));
	next_storage_26->tag = "id";
	next_storage_25->nexts["id"].push_back(next_storage_26);
	XMLData* next_storage_27 = new XMLData(std::string("640.0"));
	next_storage_27->tag = "x";
	next_storage_25->nexts["x"].push_back(next_storage_27);
	XMLData* next_storage_28 = new XMLData(std::string("96.0"));
	next_storage_28->tag = "y";
	next_storage_25->nexts["y"].push_back(next_storage_28);
	XMLData* next_storage_29 = new XMLData(std::string("128.0"));
	next_storage_29->tag = "width";
	next_storage_25->nexts["width"].push_back(next_storage_29);
	XMLData* next_storage_30 = new XMLData(std::string("64.0"));
	next_storage_30->tag = "height";
	next_storage_25->nexts["height"].push_back(next_storage_30);
	next_storage_0->nexts["rect"].push_back(next_storage_25);
	XMLData* next_storage_31 = new XMLData(std::string("		"));
	next_storage_31->tag = "rect";
	XMLData* next_storage_32 = new XMLData(std::string("5"));
	next_storage_32->tag = "id";
	next_storage_31->nexts["id"].push_back(next_storage_32);
	XMLData* next_storage_33 = new XMLData(std::string("800.0"));
	next_storage_33->tag = "x";
	next_storage_31->nexts["x"].push_back(next_storage_33);
	XMLData* next_storage_34 = new XMLData(std::string("96.0"));
	next_storage_34->tag = "y";
	next_storage_31->nexts["y"].push_back(next_storage_34);
	XMLData* next_storage_35 = new XMLData(std::string("32.0"));
	next_storage_35->tag = "width";
	next_storage_31->nexts["width"].push_back(next_storage_35);
	XMLData* next_storage_36 = new XMLData(std::string("64.0"));
	next_storage_36->tag = "height";
	next_storage_31->nexts["height"].push_back(next_storage_36);
	next_storage_0->nexts["rect"].push_back(next_storage_31);
	XMLData* next_storage_37 = new XMLData(std::string("		"));
	next_storage_37->tag = "rect";
	XMLData* next_storage_38 = new XMLData(std::string("6"));
	next_storage_38->tag = "id";
	next_storage_37->nexts["id"].push_back(next_storage_38);
	XMLData* next_storage_39 = new XMLData(std::string("880.0"));
	next_storage_39->tag = "x";
	next_storage_37->nexts["x"].push_back(next_storage_39);
	XMLData* next_storage_40 = new XMLData(std::string("96.0"));
	next_storage_40->tag = "y";
	next_storage_37->nexts["y"].push_back(next_storage_40);
	XMLData* next_storage_41 = new XMLData(std::string("48.0"));
	next_storage_41->tag = "width";
	next_storage_37->nexts["width"].push_back(next_storage_41);
	XMLData* next_storage_42 = new XMLData(std::string("64.0"));
	next_storage_42->tag = "height";
	next_storage_37->nexts["height"].push_back(next_storage_42);
	next_storage_0->nexts["rect"].push_back(next_storage_37);
	XMLData* next_storage_43 = new XMLData(std::string("		"));
	next_storage_43->tag = "rect";
	XMLData* next_storage_44 = new XMLData(std::string("7"));
	next_storage_44->tag = "id";
	next_storage_43->nexts["id"].push_back(next_storage_44);
	XMLData* next_storage_45 = new XMLData(std::string("160.0"));
	next_storage_45->tag = "x";
	next_storage_43->nexts["x"].push_back(next_storage_45);
	XMLData* next_storage_46 = new XMLData(std::string("208.0"));
	next_storage_46->tag = "y";
	next_storage_43->nexts["y"].push_back(next_storage_46);
	XMLData* next_storage_47 = new XMLData(std::string("32.0"));
	next_storage_47->tag = "width";
	next_storage_43->nexts["width"].push_back(next_storage_47);
	XMLData* next_storage_48 = new XMLData(std::string("48.0"));
	next_storage_48->tag = "height";
	next_storage_43->nexts["height"].push_back(next_storage_48);
	next_storage_0->nexts["rect"].push_back(next_storage_43);
	XMLData* next_storage_49 = new XMLData(std::string("		"));
	next_storage_49->tag = "rect";
	XMLData* next_storage_50 = new XMLData(std::string("8"));
	next_storage_50->tag = "id";
	next_storage_49->nexts["id"].push_back(next_storage_50);
	XMLData* next_storage_51 = new XMLData(std::string("480.0"));
	next_storage_51->tag = "x";
	next_storage_49->nexts["x"].push_back(next_storage_51);
	XMLData* next_storage_52 = new XMLData(std::string("208.0"));
	next_storage_52->tag = "y";
	next_storage_49->nexts["y"].push_back(next_storage_52);
	XMLData* next_storage_53 = new XMLData(std::string("32.0"));
	next_storage_53->tag = "width";
	next_storage_49->nexts["width"].push_back(next_storage_53);
	XMLData* next_storage_54 = new XMLData(std::string("48.0"));
	next_storage_54->tag = "height";
	next_storage_49->nexts["height"].push_back(next_storage_54);
	next_storage_0->nexts["rect"].push_back(next_storage_49);
	XMLData* next_storage_55 = new XMLData(std::string("		"));
	next_storage_55->tag = "rect";
	XMLData* next_storage_56 = new XMLData(std::string("9"));
	next_storage_56->tag = "id";
	next_storage_55->nexts["id"].push_back(next_storage_56);
	XMLData* next_storage_57 = new XMLData(std::string("800.0"));
	next_storage_57->tag = "x";
	next_storage_55->nexts["x"].push_back(next_storage_57);
	XMLData* next_storage_58 = new XMLData(std::string("208.0"));
	next_storage_58->tag = "y";
	next_storage_55->nexts["y"].push_back(next_storage_58);
	XMLData* next_storage_59 = new XMLData(std::string("32.0"));
	next_storage_59->tag = "width";
	next_storage_55->nexts["width"].push_back(next_storage_59);
	XMLData* next_storage_60 = new XMLData(std::string("48.0"));
	next_storage_60->tag = "height";
	next_storage_55->nexts["height"].push_back(next_storage_60);
	next_storage_0->nexts["rect"].push_back(next_storage_55);
	XMLData* next_storage_61 = new XMLData(std::string("		"));
	next_storage_61->tag = "rect";
	XMLData* next_storage_62 = new XMLData(std::string("10"));
	next_storage_62->tag = "id";
	next_storage_61->nexts["id"].push_back(next_storage_62);
	XMLData* next_storage_63 = new XMLData(std::string("80.0"));
	next_storage_63->tag = "x";
	next_storage_61->nexts["x"].push_back(next_storage_63);
	XMLData* next_storage_64 = new XMLData(std::string("384.0"));
	next_storage_64->tag = "y";
	next_storage_61->nexts["y"].push_back(next_storage_64);
	XMLData* next_storage_65 = new XMLData(std::string("48.0"));
	next_storage_65->tag = "width";
	next_storage_61->nexts["width"].push_back(next_storage_65);
	XMLData* next_storage_66 = new XMLData(std::string("128.0"));
	next_storage_66->tag = "height";
	next_storage_61->nexts["height"].push_back(next_storage_66);
	next_storage_0->nexts["rect"].push_back(next_storage_61);
	XMLData* next_storage_67 = new XMLData(std::string("		"));
	next_storage_67->tag = "rect";
	XMLData* next_storage_68 = new XMLData(std::string("11"));
	next_storage_68->tag = "id";
	next_storage_67->nexts["id"].push_back(next_storage_68);
	XMLData* next_storage_69 = new XMLData(std::string("160.0"));
	next_storage_69->tag = "x";
	next_storage_67->nexts["x"].push_back(next_storage_69);
	XMLData* next_storage_70 = new XMLData(std::string("384.0"));
	next_storage_70->tag = "y";
	next_storage_67->nexts["y"].push_back(next_storage_70);
	XMLData* next_storage_71 = new XMLData(std::string("32.0"));
	next_storage_71->tag = "width";
	next_storage_67->nexts["width"].push_back(next_storage_71);
	XMLData* next_storage_72 = new XMLData(std::string("128.0"));
	next_storage_72->tag = "height";
	next_storage_67->nexts["height"].push_back(next_storage_72);
	next_storage_0->nexts["rect"].push_back(next_storage_67);
	XMLData* next_storage_73 = new XMLData(std::string("		"));
	next_storage_73->tag = "rect";
	XMLData* next_storage_74 = new XMLData(std::string("12"));
	next_storage_74->tag = "id";
	next_storage_73->nexts["id"].push_back(next_storage_74);
	XMLData* next_storage_75 = new XMLData(std::string("240.0"));
	next_storage_75->tag = "x";
	next_storage_73->nexts["x"].push_back(next_storage_75);
	XMLData* next_storage_76 = new XMLData(std::string("384.0"));
	next_storage_76->tag = "y";
	next_storage_73->nexts["y"].push_back(next_storage_76);
	XMLData* next_storage_77 = new XMLData(std::string("48.0"));
	next_storage_77->tag = "width";
	next_storage_73->nexts["width"].push_back(next_storage_77);
	XMLData* next_storage_78 = new XMLData(std::string("128.0"));
	next_storage_78->tag = "height";
	next_storage_73->nexts["height"].push_back(next_storage_78);
	next_storage_0->nexts["rect"].push_back(next_storage_73);
	XMLData* next_storage_79 = new XMLData(std::string("		"));
	next_storage_79->tag = "rect";
	XMLData* next_storage_80 = new XMLData(std::string("13"));
	next_storage_80->tag = "id";
	next_storage_79->nexts["id"].push_back(next_storage_80);
	XMLData* next_storage_81 = new XMLData(std::string("400.0"));
	next_storage_81->tag = "x";
	next_storage_79->nexts["x"].push_back(next_storage_81);
	XMLData* next_storage_82 = new XMLData(std::string("384.0"));
	next_storage_82->tag = "y";
	next_storage_79->nexts["y"].push_back(next_storage_82);
	XMLData* next_storage_83 = new XMLData(std::string("48.0"));
	next_storage_83->tag = "width";
	next_storage_79->nexts["width"].push_back(next_storage_83);
	XMLData* next_storage_84 = new XMLData(std::string("128.0"));
	next_storage_84->tag = "height";
	next_storage_79->nexts["height"].push_back(next_storage_84);
	next_storage_0->nexts["rect"].push_back(next_storage_79);
	XMLData* next_storage_85 = new XMLData(std::string("		"));
	next_storage_85->tag = "rect";
	XMLData* next_storage_86 = new XMLData(std::string("14"));
	next_storage_86->tag = "id";
	next_storage_85->nexts["id"].push_back(next_storage_86);
	XMLData* next_storage_87 = new XMLData(std::string("480.0"));
	next_storage_87->tag = "x";
	next_storage_85->nexts["x"].push_back(next_storage_87);
	XMLData* next_storage_88 = new XMLData(std::string("384.0"));
	next_storage_88->tag = "y";
	next_storage_85->nexts["y"].push_back(next_storage_88);
	XMLData* next_storage_89 = new XMLData(std::string("32.0"));
	next_storage_89->tag = "width";
	next_storage_85->nexts["width"].push_back(next_storage_89);
	XMLData* next_storage_90 = new XMLData(std::string("128.0"));
	next_storage_90->tag = "height";
	next_storage_85->nexts["height"].push_back(next_storage_90);
	next_storage_0->nexts["rect"].push_back(next_storage_85);
	XMLData* next_storage_91 = new XMLData(std::string("		"));
	next_storage_91->tag = "rect";
	XMLData* next_storage_92 = new XMLData(std::string("15"));
	next_storage_92->tag = "id";
	next_storage_91->nexts["id"].push_back(next_storage_92);
	XMLData* next_storage_93 = new XMLData(std::string("640.0"));
	next_storage_93->tag = "x";
	next_storage_91->nexts["x"].push_back(next_storage_93);
	XMLData* next_storage_94 = new XMLData(std::string("384.0"));
	next_storage_94->tag = "y";
	next_storage_91->nexts["y"].push_back(next_storage_94);
	XMLData* next_storage_95 = new XMLData(std::string("128.0"));
	next_storage_95->tag = "width";
	next_storage_91->nexts["width"].push_back(next_storage_95);
	XMLData* next_storage_96 = new XMLData(std::string("128.0"));
	next_storage_96->tag = "height";
	next_storage_91->nexts["height"].push_back(next_storage_96);
	next_storage_0->nexts["rect"].push_back(next_storage_91);
	XMLData* next_storage_97 = new XMLData(std::string("		"));
	next_storage_97->tag = "rect";
	XMLData* next_storage_98 = new XMLData(std::string("16"));
	next_storage_98->tag = "id";
	next_storage_97->nexts["id"].push_back(next_storage_98);
	XMLData* next_storage_99 = new XMLData(std::string("800.0"));
	next_storage_99->tag = "x";
	next_storage_97->nexts["x"].push_back(next_storage_99);
	XMLData* next_storage_100 = new XMLData(std::string("384.0"));
	next_storage_100->tag = "y";
	next_storage_97->nexts["y"].push_back(next_storage_100);
	XMLData* next_storage_101 = new XMLData(std::string("32.0"));
	next_storage_101->tag = "width";
	next_storage_97->nexts["width"].push_back(next_storage_101);
	XMLData* next_storage_102 = new XMLData(std::string("128.0"));
	next_storage_102->tag = "height";
	next_storage_97->nexts["height"].push_back(next_storage_102);
	next_storage_0->nexts["rect"].push_back(next_storage_97);
	XMLData* next_storage_103 = new XMLData(std::string("		"));
	next_storage_103->tag = "rect";
	XMLData* next_storage_104 = new XMLData(std::string("17"));
	next_storage_104->tag = "id";
	next_storage_103->nexts["id"].push_back(next_storage_104);
	XMLData* next_storage_105 = new XMLData(std::string("880.0"));
	next_storage_105->tag = "x";
	next_storage_103->nexts["x"].push_back(next_storage_105);
	XMLData* next_storage_106 = new XMLData(std::string("384.0"));
	next_storage_106->tag = "y";
	next_storage_103->nexts["y"].push_back(next_storage_106);
	XMLData* next_storage_107 = new XMLData(std::string("48.0"));
	next_storage_107->tag = "width";
	next_storage_103->nexts["width"].push_back(next_storage_107);
	XMLData* next_storage_108 = new XMLData(std::string("128.0"));
	next_storage_108->tag = "height";
	next_storage_103->nexts["height"].push_back(next_storage_108);
	next_storage_0->nexts["rect"].push_back(next_storage_103);
	return next_storage_0;
}