#pragma once

#include <string>
#include <map>
#include <vector>
#include "xml_data.h"

inline XMLData* slime_anim_data(){
	XMLData* next_storage_0 = new XMLData(std::string(""));
	next_storage_0->tag = "data";
	XMLData* next_storage_1 = new XMLData(std::string(""));
	next_storage_1->tag = "animation";
	XMLData* next_storage_2 = new XMLData(std::string(""));
	next_storage_2->tag = "frame";
	XMLData* next_storage_3 = new XMLData(std::string("./resource/imgs/walk/front/slime_front_1.png"));
	next_storage_3->tag = "filename";
	next_storage_2->nexts["filename"].push_back(next_storage_3);
	XMLData* next_storage_4 = new XMLData(std::string("200"));
	next_storage_4->tag = "duration";
	next_storage_2->nexts["duration"].push_back(next_storage_4);
	next_storage_1->nexts["frame"].push_back(next_storage_2);
	next_storage_0->nexts["animation"].push_back(next_storage_1);
	XMLData* next_storage_5 = new XMLData(std::string(""));
	next_storage_5->tag = "animation";
	XMLData* next_storage_6 = new XMLData(std::string(""));
	next_storage_6->tag = "frame";
	XMLData* next_storage_7 = new XMLData(std::string("./resource/imgs/walk/left/slime_left_1.png"));
	next_storage_7->tag = "filename";
	next_storage_6->nexts["filename"].push_back(next_storage_7);
	XMLData* next_storage_8 = new XMLData(std::string("200"));
	next_storage_8->tag = "duration";
	next_storage_6->nexts["duration"].push_back(next_storage_8);
	next_storage_5->nexts["frame"].push_back(next_storage_6);
	next_storage_0->nexts["animation"].push_back(next_storage_5);
	XMLData* next_storage_9 = new XMLData(std::string(""));
	next_storage_9->tag = "animation";
	XMLData* next_storage_10 = new XMLData(std::string(""));
	next_storage_10->tag = "frame";
	XMLData* next_storage_11 = new XMLData(std::string("./resource/imgs/walk/right/slime_right_1.png"));
	next_storage_11->tag = "filename";
	next_storage_10->nexts["filename"].push_back(next_storage_11);
	XMLData* next_storage_12 = new XMLData(std::string("200"));
	next_storage_12->tag = "duration";
	next_storage_10->nexts["duration"].push_back(next_storage_12);
	next_storage_9->nexts["frame"].push_back(next_storage_10);
	next_storage_0->nexts["animation"].push_back(next_storage_9);
	XMLData* next_storage_13 = new XMLData(std::string(""));
	next_storage_13->tag = "animation";
	XMLData* next_storage_14 = new XMLData(std::string(""));
	next_storage_14->tag = "frame";
	XMLData* next_storage_15 = new XMLData(std::string("./resource/imgs/walk/back/slime_back_1.png"));
	next_storage_15->tag = "filename";
	next_storage_14->nexts["filename"].push_back(next_storage_15);
	XMLData* next_storage_16 = new XMLData(std::string("200"));
	next_storage_16->tag = "duration";
	next_storage_14->nexts["duration"].push_back(next_storage_16);
	next_storage_13->nexts["frame"].push_back(next_storage_14);
	next_storage_0->nexts["animation"].push_back(next_storage_13);
	XMLData* next_storage_17 = new XMLData(std::string(""));
	next_storage_17->tag = "animation";
	XMLData* next_storage_18 = new XMLData(std::string(""));
	next_storage_18->tag = "frame";
	XMLData* next_storage_19 = new XMLData(std::string("./resource/imgs/walk/front/slime_front_1.png"));
	next_storage_19->tag = "filename";
	next_storage_18->nexts["filename"].push_back(next_storage_19);
	XMLData* next_storage_20 = new XMLData(std::string("200"));
	next_storage_20->tag = "duration";
	next_storage_18->nexts["duration"].push_back(next_storage_20);
	next_storage_17->nexts["frame"].push_back(next_storage_18);
	XMLData* next_storage_21 = new XMLData(std::string(""));
	next_storage_21->tag = "frame";
	XMLData* next_storage_22 = new XMLData(std::string("./resource/imgs/walk/front/slime_front_2.png"));
	next_storage_22->tag = "filename";
	next_storage_21->nexts["filename"].push_back(next_storage_22);
	XMLData* next_storage_23 = new XMLData(std::string("200"));
	next_storage_23->tag = "duration";
	next_storage_21->nexts["duration"].push_back(next_storage_23);
	next_storage_17->nexts["frame"].push_back(next_storage_21);
	XMLData* next_storage_24 = new XMLData(std::string(""));
	next_storage_24->tag = "frame";
	XMLData* next_storage_25 = new XMLData(std::string("./resource/imgs/walk/front/slime_front_1.png"));
	next_storage_25->tag = "filename";
	next_storage_24->nexts["filename"].push_back(next_storage_25);
	XMLData* next_storage_26 = new XMLData(std::string("200"));
	next_storage_26->tag = "duration";
	next_storage_24->nexts["duration"].push_back(next_storage_26);
	next_storage_17->nexts["frame"].push_back(next_storage_24);
	XMLData* next_storage_27 = new XMLData(std::string(""));
	next_storage_27->tag = "frame";
	XMLData* next_storage_28 = new XMLData(std::string("./resource/imgs/walk/front/slime_front_3.png"));
	next_storage_28->tag = "filename";
	next_storage_27->nexts["filename"].push_back(next_storage_28);
	XMLData* next_storage_29 = new XMLData(std::string("200"));
	next_storage_29->tag = "duration";
	next_storage_27->nexts["duration"].push_back(next_storage_29);
	next_storage_17->nexts["frame"].push_back(next_storage_27);
	next_storage_0->nexts["animation"].push_back(next_storage_17);
	XMLData* next_storage_30 = new XMLData(std::string(""));
	next_storage_30->tag = "animation";
	XMLData* next_storage_31 = new XMLData(std::string(""));
	next_storage_31->tag = "frame";
	XMLData* next_storage_32 = new XMLData(std::string("./resource/imgs/walk/left/slime_left_1.png"));
	next_storage_32->tag = "filename";
	next_storage_31->nexts["filename"].push_back(next_storage_32);
	XMLData* next_storage_33 = new XMLData(std::string("200"));
	next_storage_33->tag = "duration";
	next_storage_31->nexts["duration"].push_back(next_storage_33);
	next_storage_30->nexts["frame"].push_back(next_storage_31);
	XMLData* next_storage_34 = new XMLData(std::string(""));
	next_storage_34->tag = "frame";
	XMLData* next_storage_35 = new XMLData(std::string("./resource/imgs/walk/left/slime_left_2.png"));
	next_storage_35->tag = "filename";
	next_storage_34->nexts["filename"].push_back(next_storage_35);
	XMLData* next_storage_36 = new XMLData(std::string("200"));
	next_storage_36->tag = "duration";
	next_storage_34->nexts["duration"].push_back(next_storage_36);
	next_storage_30->nexts["frame"].push_back(next_storage_34);
	XMLData* next_storage_37 = new XMLData(std::string(""));
	next_storage_37->tag = "frame";
	XMLData* next_storage_38 = new XMLData(std::string("./resource/imgs/walk/left/slime_left_1.png"));
	next_storage_38->tag = "filename";
	next_storage_37->nexts["filename"].push_back(next_storage_38);
	XMLData* next_storage_39 = new XMLData(std::string("200"));
	next_storage_39->tag = "duration";
	next_storage_37->nexts["duration"].push_back(next_storage_39);
	next_storage_30->nexts["frame"].push_back(next_storage_37);
	XMLData* next_storage_40 = new XMLData(std::string(""));
	next_storage_40->tag = "frame";
	XMLData* next_storage_41 = new XMLData(std::string("./resource/imgs/walk/left/slime_left_3.png"));
	next_storage_41->tag = "filename";
	next_storage_40->nexts["filename"].push_back(next_storage_41);
	XMLData* next_storage_42 = new XMLData(std::string("200"));
	next_storage_42->tag = "duration";
	next_storage_40->nexts["duration"].push_back(next_storage_42);
	next_storage_30->nexts["frame"].push_back(next_storage_40);
	next_storage_0->nexts["animation"].push_back(next_storage_30);
	XMLData* next_storage_43 = new XMLData(std::string(""));
	next_storage_43->tag = "animation";
	XMLData* next_storage_44 = new XMLData(std::string(""));
	next_storage_44->tag = "frame";
	XMLData* next_storage_45 = new XMLData(std::string("./resource/imgs/walk/right/slime_right_1.png"));
	next_storage_45->tag = "filename";
	next_storage_44->nexts["filename"].push_back(next_storage_45);
	XMLData* next_storage_46 = new XMLData(std::string("200"));
	next_storage_46->tag = "duration";
	next_storage_44->nexts["duration"].push_back(next_storage_46);
	next_storage_43->nexts["frame"].push_back(next_storage_44);
	XMLData* next_storage_47 = new XMLData(std::string(""));
	next_storage_47->tag = "frame";
	XMLData* next_storage_48 = new XMLData(std::string("./resource/imgs/walk/right/slime_right_2.png"));
	next_storage_48->tag = "filename";
	next_storage_47->nexts["filename"].push_back(next_storage_48);
	XMLData* next_storage_49 = new XMLData(std::string("200"));
	next_storage_49->tag = "duration";
	next_storage_47->nexts["duration"].push_back(next_storage_49);
	next_storage_43->nexts["frame"].push_back(next_storage_47);
	XMLData* next_storage_50 = new XMLData(std::string(""));
	next_storage_50->tag = "frame";
	XMLData* next_storage_51 = new XMLData(std::string("./resource/imgs/walk/right/slime_right_1.png"));
	next_storage_51->tag = "filename";
	next_storage_50->nexts["filename"].push_back(next_storage_51);
	XMLData* next_storage_52 = new XMLData(std::string("200"));
	next_storage_52->tag = "duration";
	next_storage_50->nexts["duration"].push_back(next_storage_52);
	next_storage_43->nexts["frame"].push_back(next_storage_50);
	XMLData* next_storage_53 = new XMLData(std::string(""));
	next_storage_53->tag = "frame";
	XMLData* next_storage_54 = new XMLData(std::string("./resource/imgs/walk/right/slime_right_3.png"));
	next_storage_54->tag = "filename";
	next_storage_53->nexts["filename"].push_back(next_storage_54);
	XMLData* next_storage_55 = new XMLData(std::string("200"));
	next_storage_55->tag = "duration";
	next_storage_53->nexts["duration"].push_back(next_storage_55);
	next_storage_43->nexts["frame"].push_back(next_storage_53);
	next_storage_0->nexts["animation"].push_back(next_storage_43);
	XMLData* next_storage_56 = new XMLData(std::string(""));
	next_storage_56->tag = "animation";
	XMLData* next_storage_57 = new XMLData(std::string(""));
	next_storage_57->tag = "frame";
	XMLData* next_storage_58 = new XMLData(std::string("./resource/imgs/walk/back/slime_back_1.png"));
	next_storage_58->tag = "filename";
	next_storage_57->nexts["filename"].push_back(next_storage_58);
	XMLData* next_storage_59 = new XMLData(std::string("200"));
	next_storage_59->tag = "duration";
	next_storage_57->nexts["duration"].push_back(next_storage_59);
	next_storage_56->nexts["frame"].push_back(next_storage_57);
	XMLData* next_storage_60 = new XMLData(std::string(""));
	next_storage_60->tag = "frame";
	XMLData* next_storage_61 = new XMLData(std::string("./resource/imgs/walk/back/slime_back_2.png"));
	next_storage_61->tag = "filename";
	next_storage_60->nexts["filename"].push_back(next_storage_61);
	XMLData* next_storage_62 = new XMLData(std::string("200"));
	next_storage_62->tag = "duration";
	next_storage_60->nexts["duration"].push_back(next_storage_62);
	next_storage_56->nexts["frame"].push_back(next_storage_60);
	XMLData* next_storage_63 = new XMLData(std::string(""));
	next_storage_63->tag = "frame";
	XMLData* next_storage_64 = new XMLData(std::string("./resource/imgs/walk/back/slime_back_1.png"));
	next_storage_64->tag = "filename";
	next_storage_63->nexts["filename"].push_back(next_storage_64);
	XMLData* next_storage_65 = new XMLData(std::string("200"));
	next_storage_65->tag = "duration";
	next_storage_63->nexts["duration"].push_back(next_storage_65);
	next_storage_56->nexts["frame"].push_back(next_storage_63);
	XMLData* next_storage_66 = new XMLData(std::string(""));
	next_storage_66->tag = "frame";
	XMLData* next_storage_67 = new XMLData(std::string("./resource/imgs/walk/back/slime_back_3.png"));
	next_storage_67->tag = "filename";
	next_storage_66->nexts["filename"].push_back(next_storage_67);
	XMLData* next_storage_68 = new XMLData(std::string("200"));
	next_storage_68->tag = "duration";
	next_storage_66->nexts["duration"].push_back(next_storage_68);
	next_storage_56->nexts["frame"].push_back(next_storage_66);
	next_storage_0->nexts["animation"].push_back(next_storage_56);
	XMLData* next_storage_69 = new XMLData(std::string(""));
	next_storage_69->tag = "animation";
	XMLData* next_storage_70 = new XMLData(std::string(""));
	next_storage_70->tag = "frame";
	XMLData* next_storage_71 = new XMLData(std::string("./resource/imgs/walk/front/slime_front_1.png"));
	next_storage_71->tag = "filename";
	next_storage_70->nexts["filename"].push_back(next_storage_71);
	XMLData* next_storage_72 = new XMLData(std::string("250"));
	next_storage_72->tag = "duration";
	next_storage_70->nexts["duration"].push_back(next_storage_72);
	next_storage_69->nexts["frame"].push_back(next_storage_70);
	XMLData* next_storage_73 = new XMLData(std::string(""));
	next_storage_73->tag = "frame";
	XMLData* next_storage_74 = new XMLData(std::string("./resource/imgs/walk/front/slime_front_2.png"));
	next_storage_74->tag = "filename";
	next_storage_73->nexts["filename"].push_back(next_storage_74);
	XMLData* next_storage_75 = new XMLData(std::string("50"));
	next_storage_75->tag = "duration";
	next_storage_73->nexts["duration"].push_back(next_storage_75);
	next_storage_69->nexts["frame"].push_back(next_storage_73);
	XMLData* next_storage_76 = new XMLData(std::string(""));
	next_storage_76->tag = "frame";
	XMLData* next_storage_77 = new XMLData(std::string("./resource/imgs/walk/front/slime_front_1.png"));
	next_storage_77->tag = "filename";
	next_storage_76->nexts["filename"].push_back(next_storage_77);
	XMLData* next_storage_78 = new XMLData(std::string("250"));
	next_storage_78->tag = "duration";
	next_storage_76->nexts["duration"].push_back(next_storage_78);
	next_storage_69->nexts["frame"].push_back(next_storage_76);
	next_storage_0->nexts["animation"].push_back(next_storage_69);
	XMLData* next_storage_79 = new XMLData(std::string(""));
	next_storage_79->tag = "animation";
	XMLData* next_storage_80 = new XMLData(std::string(""));
	next_storage_80->tag = "frame";
	XMLData* next_storage_81 = new XMLData(std::string("./resource/imgs/walk/front/slime_left_1.png"));
	next_storage_81->tag = "filename";
	next_storage_80->nexts["filename"].push_back(next_storage_81);
	XMLData* next_storage_82 = new XMLData(std::string("250"));
	next_storage_82->tag = "duration";
	next_storage_80->nexts["duration"].push_back(next_storage_82);
	next_storage_79->nexts["frame"].push_back(next_storage_80);
	XMLData* next_storage_83 = new XMLData(std::string(""));
	next_storage_83->tag = "frame";
	XMLData* next_storage_84 = new XMLData(std::string("./resource/imgs/walk/front/slime_left_2.png"));
	next_storage_84->tag = "filename";
	next_storage_83->nexts["filename"].push_back(next_storage_84);
	XMLData* next_storage_85 = new XMLData(std::string("50"));
	next_storage_85->tag = "duration";
	next_storage_83->nexts["duration"].push_back(next_storage_85);
	next_storage_79->nexts["frame"].push_back(next_storage_83);
	XMLData* next_storage_86 = new XMLData(std::string(""));
	next_storage_86->tag = "frame";
	XMLData* next_storage_87 = new XMLData(std::string("./resource/imgs/walk/front/slime_left_1.png"));
	next_storage_87->tag = "filename";
	next_storage_86->nexts["filename"].push_back(next_storage_87);
	XMLData* next_storage_88 = new XMLData(std::string("250"));
	next_storage_88->tag = "duration";
	next_storage_86->nexts["duration"].push_back(next_storage_88);
	next_storage_79->nexts["frame"].push_back(next_storage_86);
	next_storage_0->nexts["animation"].push_back(next_storage_79);
	XMLData* next_storage_89 = new XMLData(std::string(""));
	next_storage_89->tag = "animation";
	XMLData* next_storage_90 = new XMLData(std::string(""));
	next_storage_90->tag = "frame";
	XMLData* next_storage_91 = new XMLData(std::string("./resource/imgs/walk/front/slime_right_1.png"));
	next_storage_91->tag = "filename";
	next_storage_90->nexts["filename"].push_back(next_storage_91);
	XMLData* next_storage_92 = new XMLData(std::string("250"));
	next_storage_92->tag = "duration";
	next_storage_90->nexts["duration"].push_back(next_storage_92);
	next_storage_89->nexts["frame"].push_back(next_storage_90);
	XMLData* next_storage_93 = new XMLData(std::string(""));
	next_storage_93->tag = "frame";
	XMLData* next_storage_94 = new XMLData(std::string("./resource/imgs/walk/front/slime_right_2.png"));
	next_storage_94->tag = "filename";
	next_storage_93->nexts["filename"].push_back(next_storage_94);
	XMLData* next_storage_95 = new XMLData(std::string("50"));
	next_storage_95->tag = "duration";
	next_storage_93->nexts["duration"].push_back(next_storage_95);
	next_storage_89->nexts["frame"].push_back(next_storage_93);
	XMLData* next_storage_96 = new XMLData(std::string(""));
	next_storage_96->tag = "frame";
	XMLData* next_storage_97 = new XMLData(std::string("./resource/imgs/walk/front/slime_right_1.png"));
	next_storage_97->tag = "filename";
	next_storage_96->nexts["filename"].push_back(next_storage_97);
	XMLData* next_storage_98 = new XMLData(std::string("250"));
	next_storage_98->tag = "duration";
	next_storage_96->nexts["duration"].push_back(next_storage_98);
	next_storage_89->nexts["frame"].push_back(next_storage_96);
	next_storage_0->nexts["animation"].push_back(next_storage_89);
	XMLData* next_storage_99 = new XMLData(std::string(""));
	next_storage_99->tag = "animation";
	XMLData* next_storage_100 = new XMLData(std::string(""));
	next_storage_100->tag = "frame";
	XMLData* next_storage_101 = new XMLData(std::string("./resource/imgs/walk/front/slime_back_1.png"));
	next_storage_101->tag = "filename";
	next_storage_100->nexts["filename"].push_back(next_storage_101);
	XMLData* next_storage_102 = new XMLData(std::string("250"));
	next_storage_102->tag = "duration";
	next_storage_100->nexts["duration"].push_back(next_storage_102);
	next_storage_99->nexts["frame"].push_back(next_storage_100);
	XMLData* next_storage_103 = new XMLData(std::string(""));
	next_storage_103->tag = "frame";
	XMLData* next_storage_104 = new XMLData(std::string("./resource/imgs/walk/front/slime_back_2.png"));
	next_storage_104->tag = "filename";
	next_storage_103->nexts["filename"].push_back(next_storage_104);
	XMLData* next_storage_105 = new XMLData(std::string("50"));
	next_storage_105->tag = "duration";
	next_storage_103->nexts["duration"].push_back(next_storage_105);
	next_storage_99->nexts["frame"].push_back(next_storage_103);
	XMLData* next_storage_106 = new XMLData(std::string(""));
	next_storage_106->tag = "frame";
	XMLData* next_storage_107 = new XMLData(std::string("./resource/imgs/walk/front/slime_back_1.png"));
	next_storage_107->tag = "filename";
	next_storage_106->nexts["filename"].push_back(next_storage_107);
	XMLData* next_storage_108 = new XMLData(std::string("250"));
	next_storage_108->tag = "duration";
	next_storage_106->nexts["duration"].push_back(next_storage_108);
	next_storage_99->nexts["frame"].push_back(next_storage_106);
	next_storage_0->nexts["animation"].push_back(next_storage_99);
	return next_storage_0;
}